version: "2"
services:
  webserver:
    image: nginx
    volumes:
      - "./content:/usr/share/nginx/html/"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/sites-available/default:/etc/nginx/sites-available/default"
    ports:
      - 80:80